name: Build APK (Final)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Guboshlepka-APK
          path: bin/*.apk
